[package]
name = "tflite-pose"
version = "0.1.0"
authors = ["Phillip Cloud <cpcloud@gmail.com>"]
edition = "2018"

[features]
default = []
gui = []

[dependencies]
anyhow = "1"
ctrlc = "3"
indicatif = "0.16"
ndarray = "0.15.2"
num-derive = "0.3"
num-traits = "0.2"
opencv = { version = "0.53.0", features = ["clang-runtime"] }
structopt = "0.3.21"
thiserror = "1"
ordered-float = "2"
itertools = "0.10"

[build-dependencies]
anyhow = "1"
bindgen = "0.58.1"
pkg-config = "0.3.19"

[profile.release]
lto = true
codegen-units = 1
